services:
  - type: web
    name: pysmt-runner
    env: python
    rootDir: pysmt
    buildCommand: pip install -r requirements.txt && echo y | pysmt-install --msat
    startCommand: python server.py
    plan: free
