services:
  - type: web
    name: pysmt-runner
    env: python
    rootDir: pysmt
    buildCommand: pip install -r requirements.txt && pysmt-install --msat --confirm
    startCommand: python server.py
    plan: free
